# -*- coding: utf-8 -*-
"""Figure3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZi93OUg45jdkVXvSSgZgBqXqCs1QmsH
"""

import numpy as np
import matplotlib.pyplot as plt

# ------------------------
# Model primitives
# ------------------------

def clip01(x):
    return np.minimum(1.0, np.maximum(0.0, x))

def simulate_path(
    J=12, T=1200,
    theta=1.0, Dbar=0.5,
    Delta=0.02, sigma=0.02,
    lam=10.0, Mbar=1.0,
    seed=0
):
    rng = np.random.default_rng(seed)

    s = rng.uniform(0, 1, size=J)
    M = np.full(J, Mbar / J)

    D_max = np.zeros(T)
    D_min = np.zeros(T)
    M_max = np.zeros(T)

    for t in range(T):
        D = theta * s
        # Record contemporaneous state (t): detection probabilities and current allocation M
        D_max[t] = D.max()
        D_min[t] = D.min()
        M_max[t] = M.max()
        
        # Noisy signal and adaptive implementation update (t -> t+1)
        Dhat = D + rng.normal(0.0, sigma, size=J)
        s = clip01(s + Delta * (Dhat < Dbar) - Delta * (Dhat > Dbar))
        
        # Illicit-flow relocation based on current detection environment (t -> t+1)
        w = np.exp(-lam * D)
        M = Mbar * w / w.sum()

    return D_max, D_min, M_max


# ------------------------
# Parameter choices
# ------------------------

regimes = [
    {"label": "Stable regime",       "Delta": 0.02,  "sigma": 0.02,  "seed": 1},
    {"label": "Multiplicity regime", "Delta": 0.055, "sigma": 0.10,  "seed": 2},
    {"label": "Severe lock-in",      "Delta": 0.07,  "sigma": 0.15,  "seed": 3},
]

# ------------------------
# Run simulations
# ------------------------

results = []
for r in regimes:
    results.append(
        simulate_path(
            Delta=r["Delta"],
            sigma=r["sigma"],
            seed=r["seed"]
        )
    )

# ------------------------
# Plot settings
# ------------------------

T_show = 300
time = np.arange(T_show)

fig, axes = plt.subplots(2, 3, figsize=(12, 6), sharex="col")

for i, (r, (D_max, D_min, M_max)) in enumerate(zip(regimes, results)):

    # ---- Top row: max/min detection probability ----
    ax = axes[0, i]
    ax.plot(time, D_max[:T_show], color="black", linewidth=1.8, label="Max $D_{j,t}$")
    ax.plot(time, D_min[:T_show], color="gray", linestyle="--", linewidth=1.8, label="Min $D_{j,t}$")

    ax.set_ylim(0, 1)
    ax.set_title(
        f"{r['label']}\nΔ={r['Delta']}, σ={r['sigma']}",
        fontsize=10
    )

    if i == 0:
        ax.set_ylabel("Detection probability")

    if i == 2:
        ax.legend(frameon=False, fontsize=8, loc="upper right")

    # ---- Bottom row: max criminal fund share ----
    ax2 = axes[1, i]
    ax2.plot(time, M_max[:T_show], color="black", linewidth=1.8, label="Max share")
    ax2.axhline(1/12, color="gray", linestyle=":", linewidth=1.5, label="Equal share")

    ax2.set_ylim(0, 1)

    if i == 0:
        ax2.set_ylabel("Criminal fund share")

    ax2.set_xlabel("Time")

    if i == 2:
        ax2.legend(frameon=False, fontsize=8, loc="upper right")

plt.tight_layout()
plt.savefig("Figure3_representative_dynamics.png", dpi=300)
plt.show()
